
    - name: Install python-pip
      apt: pkg=python-pip update_cache=yes
      sudo: yes
      tags:
      - docker
      - run

    - name: Install docker apt repository
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main' state=present
      sudo: yes
      tags:
      - docker
      - run

    - name: Add docker apt key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
      sudo: yes
      tags:
      - docker
      - run

    - name: Update apt cache
      apt: update_cache=yes
      sudo: yes
      tags:
      - docker
      - run

    - name: Install docker and recommended packages
      apt: name={{ item }} update_cache=yes
      sudo: yes
      with_items:
      - linux-image-extra-{{ ansible_kernel }}
      - linux-image-extra-virtual
      - docker-engine
      tags:
      - docker
      - run

    - name: Install docker-compose
      pip: name=docker-compose
      sudo: yes
      tags:
      - docker
      - run
