
    - name: Install python3-pip
      apt: pkg=python3-pip update_cache=yes
      become: yes
      tags:
      - docker
      - run

    - name: Upgrade pip3
      pip: name=pip extra_args=--upgrade executable=/usr/bin/pip3
      become: yes
      tags:
      - docker
      - run

    - name: Install docker apt repository
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main' state=present
      become: yes
      tags:
      - docker
      - run

    - name: Add docker apt key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
      become: yes
      tags:
      - docker
      - run

    - name: Update apt cache
      apt: update_cache=yes
      become: yes
      tags:
      - docker
      - run

    - name: Install docker and recommended packages
      apt: name={{ item }} update_cache=yes
      become: yes
      with_items:
      - linux-image-extra-{{ ansible_kernel }}
      - linux-image-extra-virtual
      - docker-engine
      tags:
      - docker
      - run

    - name: Install docker-compose
      pip: name=docker-compose executable=/usr/bin/pip3
      become: yes
      tags:
      - docker
      - run
